<a href="https://colab.research.google.com/github/EvgeniyZhuyko/MTT26/blob/LuaLocalScryptAgent/lualocalscriptagent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!sudo apt-get update && sudo apt-get install -y zstd

Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [88.5 kB]
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:7 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,497 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:10 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.0 MB]
Get:11 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:13 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:14 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,917 kB]
Hit:15 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,226 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,965 kB]
Get:18 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.8 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,622 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,143 kB]
Get:21 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,311 kB]
Get:22 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,889 kB]
Fetched 41.1 MB in 4s (10.2 MB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  zstd
0 upgraded, 1 newly installed, 0 to remove and 73 not upgraded.
Need to get 603 kB of archives.
After this operation, 1,695 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 zstd amd64 1.4.8+dfsg-3build1 [603 kB]
Fetched 603 kB in 1s (1,035 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package zstd.
(Reading database ... 122354 files and directories currently installed.)
Preparing to unpack .../zstd_1.4.8+dfsg-3build1_amd64.deb ...
Unpacking zstd (1.4.8+dfsg-3build1) ...
Setting up zstd (1.4.8+dfsg-3build1) ...
Processing triggers for man-db (2.10.2-1) ...

In [ ]:
# Установка Ollama
!curl -fsSL https://ollama.com/install.sh | sh

# Запуск сервера Ollama в фоне
import subprocess
subprocess.Popen(["ollama", "serve"])

# Скачивание модели
!ollama pull nuprl/MultiPLCoder-1b

>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.

Error: pull model manifest: file does not exist

In [ ]:
import subprocess
import time

# Запускаем Ollama в фоне
process = subprocess.Popen(["ollama", "serve"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
print("Ollama сервер запускается...")
time.sleep(5)  # Даем серверу 5 секунд на инициализацию
print("Готово, сервер работает.")

Ollama сервер запускается...
Готово, сервер работает.

In [ ]:
!curl -s http://localhost:11434/api/tags

{"models":[]}

In [ ]:
!ollama pull tinyllama

In [ ]:
!ollama run tinyllama "Привет, как дела?"

Доброго времени суток! Скажу, что работаю.

Она: Привет, как дела?

Уадим: Одно время, у меня работал с помощником.

Она: С чего возникли проблемы?

Уадим: А именно, счетчик считывал неверное количество дней в календаре. Это
Это создало огромную заботу в организации, а значит, пришлось сменить код.
И всё это долгое время было трудно-вряд ли быстро. Наконец, мы нашли способ
способ и поговорили про то, что нужно сделать для того чтобы сработало.

Она: Зачем это вам интересно?

Уадим: Это важное для вас, если вы работаете в организации. Возможно, это п
проблема нескольких организаций.

Она: Я не могу быть слишком простой. Как всегда вы надеюсь помочь, но не ст
стоит смущать меня.

Уадим: Мне кажется, что вас можно забыть, как привыкать к вашим мероприятия
мероприятиям. Единственное, что это может привести к большему количеству пр
проблем, это неправильный код, который был добавлен в программу, и мы должн
должны уйти на его поддержку.

Она: Так, как эти проблемы с собраниями в календаре решились?

Уадим: Вы понимаете, что это сложно. Мы были заинтересованы в том, чтобы до
добавить функцию к коду. Я попрошу вас сделать что-нибудь. Если вы хотите у
узнать больше о том, как сделать это, можете позвонить нам или просить наше
нашего партнера приступить к работе на этой тематике. Это будет быстро и эф
эффективно.

Она: Я понимаю. Но как это помочь?

Уадим: Мы обещаем, что немедленно сообщим вам о результатах нашей работы. Е
Если вы хотите, чтобы мы связались с другими организациями, которые также з
заинтересованы в том, как изменить код или сделать это, не волнуйтесь.

Она: Спасибо за рассказ. Может я понимаю?

In [ ]:
!pip install -q unsloth transformers datasets accelerate peft bitsandbytes xformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 MB 12.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 120.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 46.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 112.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 15.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 41.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 418.4/418.4 kB 41.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 119.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.2/185.2 kB 22.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 111.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.8/224.8 kB 25.5 MB/s eta 0:00:00

In [1]:
import json
from google.colab import files
import os

# ========== НАСТРОЙКИ ПУТЕЙ ДЛЯ COLAB ==========
INPUT_FILENAME = "50 диалогов.txt"
OUTPUT_FILENAME = "analyst_dataset.jsonl"
INPUT_PATH = f"/media/{INPUT_FILENAME}"
OUTPUT_PATH = f"/media/{OUTPUT_FILENAME}"

# Инструкция для аналитика (фиксированная)
INSTRUCTION = """[ROLE: analyst]

Assess if a Lua generation task is specific enough to act on.
CLEAR = names field paths (wf.vars.*), the operation, and expected result.
UNCLEAR = missing field names, data shape, or transformation logic.
If CLEAR: respond PROCEED. If UNCLEAR: ask 1-3 questions. No preamble."""

# ========== ЗАГРУЗКА ФАЙЛА (если его нет) ==========
if not os.path.exists(INPUT_PATH):
    print(f"Файл {INPUT_FILENAME} не найден. Пожалуйста, загрузите его:")
    uploaded = files.upload()
    for fname in uploaded.keys():
        os.rename(fname, INPUT_PATH)
        print(f"Файл сохранён как {INPUT_PATH}")

# ========== ЗАГРУЗКА ДИАЛОГОВ ==========
with open(INPUT_PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

# Приведение к единому формату: список диалогов, каждый диалог — список сообщений {role, content}
if isinstance(data, list) and all(isinstance(d, dict) and "dialog" in d for d in data):
    dialogs = [item["dialog"] for item in data]
elif isinstance(data, list) and all(isinstance(d, list) for d in data):
    dialogs = data
else:
    raise ValueError("Неизвестный формат. Ожидается массив с ключом 'dialog' или массив списков сообщений.")

print(f"Загружено диалогов: {len(dialogs)}")

# ========== ПОСТРОЕНИЕ ПРИМЕРОВ ДЛЯ АНАЛИТИКА ==========
all_examples = []
for dialog_idx, dialog in enumerate(dialogs):
    # Находим первое сообщение пользователя (нечёткая задача)
    user_messages = [msg for msg in dialog if msg["role"] == "user"]
    assistant_messages = [msg for msg in dialog if msg["role"] == "assistant"]

    if not user_messages or not assistant_messages:
        print(f"Диалог {dialog_idx+1} пропущен: нет сообщений пользователя или ассистента")
        continue

    first_user_msg = user_messages[0]["content"]
    first_assistant_msg = assistant_messages[0]["content"]  # это и есть уточняющие вопросы

    # Формируем пример для аналитика
    example = {
        "instruction": INSTRUCTION,
        "input": first_user_msg,   # нечёткая задача
        "output": first_assistant_msg  # вопросы
    }
    all_examples.append(example)

print(f"Создано примеров для аналитика: {len(all_examples)}")

# ========== СОХРАНЕНИЕ ==========
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    for ex in all_examples:
        f.write(json.dumps(ex, ensure_ascii=False) + "\n")

print(f"Датасет сохранён в {OUTPUT_PATH}")

# ========== СКАЧИВАНИЕ ==========
files.download(OUTPUT_PATH)

Загружено диалогов: 53
Создано примеров для аналитика: 53
Датасет сохранён в /media/analyst_dataset.jsonl

In [2]:
import json
import random
from google.colab import files
import os

# ==================== НАСТРОЙКИ ====================
OUTPUT_FILENAME = "critic_data.jsonl"
OUTPUT_PATH = f"/media/{OUTPUT_FILENAME}"

# Инструкция для критика
INSTRUCTION = """[ROLE: critic]

Review Lua code for the Octapi LowCode platform.
Check: wf.vars.* access (no bare names), local declarations, _utils.array.new() for new arrays, ends with return, no forbidden calls.
If correct: LGTM. If issues: list as "Line N: problem". Be concise."""

# ==================== БАНК КОРРЕКТНЫХ КОНСТРУКЦИЙ ====================
# Правильные примеры на основе вашего файла и найденных источников

# 1. Работа с таблицами / массивами (источники: [2†L6-L7], [8†L14-L15])
TABLE_EXAMPLES = {
    "sum": """local total = 0
for _, item in ipairs(wf.vars.products) do
  total = total + (item.price or 0)
end
return total""",
    "filter": """local result = _utils.array.new()
local items = wf.vars.orders
for _, item in ipairs(items) do
  if item.region == "VLG" then
    table.insert(result, item)
  end
end
return result""",
    "collect": """local result = _utils.array.new()
for _, item in ipairs(wf.vars.events) do
  table.insert(result, item.type)
end
return result""",
    "first_element": """return wf.vars.packages[1]""",
    "last_element": """return wf.vars.items[#wf.vars.items]""",
    "length": """return #wf.vars.shipments""",
    "max": """local max = nil
for _, item in ipairs(wf.vars.records) do
  if max == nil or item.total > max then
    max = item.total
  end
end
return max""",
    "create_array": """local result = _utils.array.new()
table.insert(result, "first")
table.insert(result, "second")
return result""",
}

# 2. Условные операторы (источник: [6†L5-L9])
CONDITIONAL_EXAMPLES = {
    "if_else": """if wf.vars.score >= 90 then
  return "A"
elseif wf.vars.score >= 80 then
  return "B"
else
  return "C"
end""",
    "check_nil": """if wf.vars.status ~= nil then
  return wf.vars.status
else
  return "unknown"
end""",
}

# 3. Функции (источник: [5†L5-L6])
FUNCTION_EXAMPLES = {
    "simple": """local function add(a, b)
  return a + b
end
return add(wf.vars.x, wf.vars.y)""",
    "recursive": """local function factorial(n)
  if n == 0 then
    return 1
  else
    return n * factorial(n - 1)
  end
end
return factorial(wf.vars.num)""",
}

# 4. Работа со строками (источник: [3†L19-L21])
STRING_EXAMPLES = {
    "upper": """return string.upper(wf.vars.title)""",
    "concat": """return wf.vars.status .. "_" .. wf.vars.email""",
    "substring": """return string.sub(wf.vars.date, 1, 4)""",
}

# 5. Комбинированные операции
MIXED_EXAMPLES = {
    "filter_and_map": """local result = _utils.array.new()
for _, item in ipairs(wf.vars.users) do
  if item.active then
    table.insert(result, item.name)
  end
end
return result""",
    "transform_date": """local d = wf.vars.delivery_date
return string.sub(d,1,4) .. "-" .. string.sub(d,5,6) .. "-" .. string.sub(d,7,8)""",
    "first_non_nil": """local fields = {"title", "priority", "region"}
for _, key in ipairs(fields) do
  if wf.vars[key] ~= nil then
    return wf.vars[key]
  end
end
return nil""",
}

# Объединяем все правильные примеры в один список
ALL_CORRECT = (list(TABLE_EXAMPLES.values()) +
               list(CONDITIONAL_EXAMPLES.values()) +
               list(FUNCTION_EXAMPLES.values()) +
               list(STRING_EXAMPLES.values()) +
               list(MIXED_EXAMPLES.values()))

# ==================== ФУНКЦИИ ДЛЯ ВНЕСЕНИЯ ОШИБОК ====================

def add_missing_local(code):
    """Удаляет local у первой переменной (если есть)"""
    if "local " in code:
        return code.replace("local ", "", 1)
    return code

def add_forbidden_call(code):
    """Добавляет запрещённый вызов io.open"""
    return "io.open('file.txt', 'r')\n" + code

def remove_return(code):
    """Удаляет return в конце"""
    lines = code.split('\n')
    if lines and lines[-1].startswith('return'):
        lines.pop()
        return '\n'.join(lines)
    return code

def use_global_var(code):
    """Превращает локальную переменную в глобальную"""
    if "local result" in code:
        return code.replace("local result", "result")
    if "local total" in code:
        return code.replace("local total", "total")
    return code

def remove_wf_prefix(code):
    """Убирает wf. у wf.vars"""
    return code.replace("wf.vars.", "vars.")

def misuse_array(code):
    """Использует {} вместо _utils.array.new()"""
    return code.replace("_utils.array.new()", "{}")

def add_jsonpath(code):
    """Добавляет строку с JsonPath синтаксисом"""
    return "$.items[0]\n" + code

def remove_nil_check(code):
    """Убирает проверку на nil (влияет на логику)"""
    return code.replace("~= nil", "").replace("== nil", "")

def add_trailing_comment(code):
    """Добавляет пояснительный комментарий после return (нарушает требование)"""
    return code + "\n-- Это пояснение нарушает правило"

def wrong_array_index(code):
    """Использует индекс 0 вместо 1 в table.insert"""
    return code.replace("table.insert(", "table.insert(..., 0, ")

# Список функций-мутаторов
ERROR_FUNCTIONS = [
    add_missing_local,
    add_forbidden_call,
    remove_return,
    use_global_var,
    remove_wf_prefix,
    misuse_array,
    add_jsonpath,
    remove_nil_check,
    add_trailing_comment,
    wrong_array_index,
]

def introduce_error(code):
    """Случайным образом применяет одну из ошибок"""
    error_func = random.choice(ERROR_FUNCTIONS)
    return error_func(code)

# ==================== ГЕНЕРАЦИЯ ПРИМЕРОВ ====================
print("Генерация датасета для критика...")

all_examples = []

# 1. Генерация корректных примеров (100 штук)
for i in range(100):
    # Выбираем случайный правильный пример и немного "перемешиваем" имена переменных для разнообразия
    base_code = random.choice(ALL_CORRECT)
    # Небольшая вариативность: заменяем названия массивов и полей
    variations = [
        ("products", "items"),
        ("orders", "transactions"),
        ("price", "value"),
        ("total", "sum"),
        ("type", "category"),
    ]
    code = base_code
    for old, new in random.sample(variations, random.randint(0, 2)):
        code = code.replace(old, new)

    example = {
        "instruction": INSTRUCTION,
        "input": code,
        "output": "LGTM"
    }
    all_examples.append(example)

# 2. Генерация некорректных примеров (100 штук)
for i in range(100):
    # Берем случайный правильный пример и вносим ошибку
    base_code = random.choice(ALL_CORRECT)
    # Для большего разнообразия, сначала слегка модифицируем базовый пример
    variations = [
        ("products", "items"),
        ("orders", "transactions"),
        ("price", "value"),
        ("total", "sum"),
        ("type", "category"),
    ]
    code = base_code
    for old, new in random.sample(variations, random.randint(0, 2)):
        code = code.replace(old, new)

    corrupted_code = introduce_error(code)

    # Генерируем отчет об ошибке (имитация реального вывода критика)
    error_report = "Line 1: potential issue detected"
    if "local " not in corrupted_code and "local" in base_code:
        error_report = "Line 1: variable is missing the `local` keyword — creates a global"
    elif "io.open" in corrupted_code:
        error_report = "Line 1: forbidden call 'io.open' — not allowed in Octapi Sandbox"
    elif "return" not in corrupted_code and "return" in base_code:
        error_report = "Line X: missing `return` statement at the end"
    elif "vars." in corrupted_code and "wf.vars" not in corrupted_code:
        error_report = "Line 1: variable 'vars' is not defined — use 'wf.vars'"
    elif "{}" in corrupted_code and "_utils.array.new()" in base_code:
        error_report = "Line 1: use '_utils.array.new()' to create new arrays, not '{}'"
    elif "$." in corrupted_code:
        error_report = "Line 1: JsonPath syntax is not allowed in Lua"
    elif "-- Это пояснение" in corrupted_code:
        error_report = "Line X: output must be ONLY raw Lua code — no comments or explanations"
    else:
        error_report = "Line 1: code does not follow Octapi LowCode rules"

    example = {
        "instruction": INSTRUCTION,
        "input": corrupted_code,
        "output": error_report
    }
    all_examples.append(example)

# Перемешиваем примеры, чтобы корректные и некорректные шли в случайном порядке
random.shuffle(all_examples)

print(f"Создано примеров: {len(all_examples)} (ожидалось 200)")

# ==================== СОХРАНЕНИЕ И ВЫГРУЗКА ====================
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    for ex in all_examples:
        f.write(json.dumps(ex, ensure_ascii=False) + "\n")

print(f"Датасет сохранён в {OUTPUT_PATH}")
files.download(OUTPUT_PATH)

Генерация датасета для критика...
Создано примеров: 200 (ожидалось 200)
Датасет сохранён в /media/critic_data.jsonl

In [4]:
# Ячейка 1: Установка всех зависимостей
!pip install -q "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install -q --no-deps xformers trl peft accelerate bitsandbytes
!pip install -q datasets sentencepiece protobuf huggingface_hub hf_transfer

print("Все зависимости успешно установлены!")

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 13.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 45.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 133.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 421.2/421.2 kB 40.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 87.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.2/185.2 kB 22.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 20.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 83.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 42.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.0/225.0 kB 22.0 MB/s eta 0:00:00
  Building wheel for unsloth (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 47.0 MB/s eta 0:00:00
Все зависимости успешно установлены!

In [5]:
# Импорт библиотек
from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments
import torch

# 1. Загрузка базовой модели с 4-битной квантизацией
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b", # Ваша базовая модель
    max_seq_length=2048, # Максимальная длина обрабатываемой последовательности
    dtype=None,
    load_in_4bit=True, # Включаем QLoRA
)

# 2. Применение LoRA-адаптера к модели
# 2. Применение LoRA-адаптера к модели
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = [
        "c_attn",   # Совмещённый модуль внимания
        "c_proj",   # Выходная проекция внимания
        "c_fc",     # Первый линейный слой MLP
        # "c_proj_mlp" # Опционально, иногда присутствует
    ],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = True,
)

# 3. Загрузка и подготовка датасета
# 3. Загрузка и подготовка датасета
dataset = load_dataset('json', data_files='/media/analyst_dataset.jsonl', split='train')

# Функция форматирования, возвращающая список
def formatting_func(examples):
    texts = []
    for instruction, output in zip(examples["instruction"], examples["output"]):
        text = f"### Instruction:\n{instruction}\n\n### Response:\n{output}"
        texts.append(text)
    return texts

# 4. Настройка и запуск тренера
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    formatting_func=formatting_func,
    max_seq_length=2048,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=10,
        num_train_epochs=3,
        learning_rate=2e-4,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=1,
        optim="adamw_8bit",
        output_dir="outputs",
    ),
)

==((====))==  Unsloth 2026.4.6: Fast Gpt_Bigcode patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

nuprl/MultiPLCoder-1b does not have a padding token! Will use pad_token = <|endoftext|>.

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/53 [00:00<?, ? examples/s]

In [7]:
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 53 | Num Epochs = 3 | Total steps = 21
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 11,108,352 of 1,148,315,648 (0.97% trained)

TrainOutput(global_step=21, training_loss=2.589076519012451, metrics={'train_runtime': 41.3699, 'train_samples_per_second': 3.843, 'train_steps_per_second': 0.508, 'total_flos': 185099815919616.0, 'train_loss': 2.589076519012451, 'epoch': 3.0})

In [11]:
import os
os.makedirs("/content/outputs/lora_adapters/analyst", exist_ok=True)

In [12]:
model.save_pretrained("/content/outputs/lora_adapters/analyst")
tokenizer.save_pretrained("/content/outputs/lora_adapters/analyst")  # токенизатор тоже лучше сохранить

('/content/outputs/lora_adapters/analyst/tokenizer_config.json',
 '/content/outputs/lora_adapters/analyst/tokenizer.json')

In [10]:
model.save_pretrained("/outputs/lora_adapters/analyst")

In [14]:
from unsloth import FastLanguageModel
import torch

# 1. Загружаем БАЗОВУЮ модель
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b",
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
)

# 2. ЗАГРУЖАЕМ АДАПТЕР (это критически важно!)
model.load_adapter("/content/drive/MyDrive/lora_adapters/analyst")

# 3. Переводим в режим инференса
FastLanguageModel.for_inference(model)

# 4. Формируем промпт ТОЧНО как в обучении
prompt = """### Instruction:
Напиши скрипт для обработки данных на Lua.

### Response:
"""

inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

# 5. Генерируем с низкой температурой для стабильности
outputs = model.generate(
    **inputs,
    max_new_tokens=256,
    temperature=0.1,
    do_sample=True,
    repetition_penalty=1.1
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

==((====))==  Unsloth 2026.4.6: Fast Gpt_Bigcode patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

nuprl/MultiPLCoder-1b does not have a padding token! Will use pad_token = <|endoftext|>.

OSError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/content/drive/MyDrive/lora_adapters/analyst'. Use `repo_type` argument if needed.

In [18]:
# ============================================
# ЯЧЕЙКА ДЛЯ ИНФЕРЕНСА АДАПТЕРА-АНАЛИТИКА (одна ячейка)
# ============================================

# 1. Установка библиотек (если ещё не установлены)
!pip install -q unsloth peft transformers accelerate bitsandbytes xformers

# 2. Импорты
from unsloth import FastLanguageModel
from peft import PeftModel
import torch

# 3. Путь к вашему адаптеру (замените при необходимости)
ADAPTER_PATH = "/outputs/lora_adapters/analyst"

# 4. Загрузка базовой модели MultiPLCoder-1b
print("Загрузка базовой модели...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b",
    max_seq_length=2048,
    load_in_4bit=True,
)

# 5. Загрузка обученного LoRA-адаптера
print("Загрузка адаптера-аналитика...")
model = PeftModel.from_pretrained(model, ADAPTER_PATH)

# 6. Переключение в режим инференса
FastLanguageModel.for_inference(model)
print("Модель готова к работе!\n")

# 7. Тестовый запрос (на русском)
prompt = """### Instruction:
Напиши скрипт для обработки данных на Lua.

### Response:
"""

# 8. Токенизация и генерация
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = model.generate(
    **inputs,
    max_new_tokens=256,
    temperature=0.1,          # Низкая температура для стабильности
    do_sample=True,
    repetition_penalty=1.1
)

# 9. Вывод результата
generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
print("=== ОТВЕТ МОДЕЛИ ===")
print(generated_text)

Загрузка базовой модели...
==((====))==  Unsloth 2026.4.6: Fast Gpt_Bigcode patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

nuprl/MultiPLCoder-1b does not have a padding token! Will use pad_token = <|endoftext|>.
Загрузка адаптера-аналитика...

Both `max_new_tokens` (=256) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Модель готова к работе!

=== ОТВЕТ МОДЕЛИ ===
### Instruction:
Напиши скрипт для обработки данных на Lua.

### Response:
```lua
local data = require "data"

if #ARGV == 1 then
  local file = io.open(ARGV[1], "r")
  if not file then
    print("file does not exist")
  else
    local content = file:read("*all")
    for line in content:gmatch("[^\n]*") do
      local fields = string.split(line, "\t")
      local action = fields[1]
      local value = fields[2]
      if action == "add" then
        data.add(value)
      elseif action == "remove" then
        data.remove(value)
      end
    end
    print(data:dump())
  end
else
  print(string.format("Usage: %s <action> <key>", ARGV[0]))
end
```

In [21]:
import json
with open('/outputs/lora_adapters/analyst/analyst_dataset.jsonl', 'r') as f:
    for i, line in enumerate(f):
        if i < 3:  # первые 3 записи
            print(json.loads(line))
        else:
            break

{'instruction': '[ROLE: analyst]\n\nAssess if a Lua generation task is specific enough to act on.\nCLEAR = names field paths (wf.vars.*), the operation, and expected result.\nUNCLEAR = missing field names, data shape, or transformation logic.\nIf CLEAR: respond PROCEED. If UNCLEAR: ask 1-3 questions. No preamble.', 'input': 'Нужен скрипт для обработки данных.', 'output': 'Уточните, пожалуйста:\n1. Откуда берутся данные? (файл, stdin, сеть?)\n2. Какой формат данных? (CSV, JSON, сырой текст?)\n3. Что именно нужно сделать с данными? (фильтрация, агрегация, преобразование?)\n4. Куда вывести результат? (файл, консоль, другой процесс?)'}
{'instruction': '[ROLE: analyst]\n\nAssess if a Lua generation task is specific enough to act on.\nCLEAR = names field paths (wf.vars.*), the operation, and expected result.\nUNCLEAR = missing field names, data shape, or transformation logic.\nIf CLEAR: respond PROCEED. If UNCLEAR: ask 1-3 questions. No preamble.', 'input': 'Нужен Lua-скрипт для автоматизации рутинных задач с файлами.', 'output': 'Какие именно задачи?\n1. Какие операции над файлами? (копирование, перемещение, переименование, удаление?)\n2. Нужна ли рекурсия по папкам?\n3. По какому критерию выбирать файлы? (расширение, дата, размер?)\n4. Должен ли скрипт выводить отчёт о выполненных действиях?'}
{'instruction': '[ROLE: analyst]\n\nAssess if a Lua generation task is specific enough to act on.\nCLEAR = names field paths (wf.vars.*), the operation, and expected result.\nUNCLEAR = missing field names, data shape, or transformation logic.\nIf CLEAR: respond PROCEED. If UNCLEAR: ask 1-3 questions. No preamble.', 'input': 'Нужно написать скрипт для взаимодействия с веб-API.', 'output': 'Уточните параметры:\n1. Какой метод HTTP? (GET, POST, PUT?)\n2. Какой URL и нужны ли заголовки (например, API-ключ)?\n3. Какие данные отправлять и в каком формате? (JSON, form-data?)\n4. Что делать с ответом? (сохранить в файл, вывести в консоль, распарсить?)'}

In [27]:
# ============================================
# ОБУЧЕНИЕ АДАПТЕРА-АНАЛИТИКА (ПРАВИЛЬНЫЙ ФОРМАТ)
# ============================================

# --- 1. Установка зависимостей ---
!pip install -q "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install -q --no-deps xformers trl peft accelerate bitsandbytes
!pip install -q datasets

# --- 2. Импорты ---
from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments
import torch
import os

# --- 3. Монтирование Google Drive (чтобы сохранить адаптер) ---
from google.colab import drive
drive.mount('/content/drive')

# --- 4. Пути (ИЗМЕНИТЕ ПОД СВОИ) ---
DATASET_PATH = "/media/analyst_dataset.jsonl"   # ваш файл .jsonl
SAVE_PATH    = "/content/drive/MyDrive/lora_adapters/analyst" # куда сохранить адаптер

os.makedirs(SAVE_PATH, exist_ok=True)

# --- 5. Загрузка базовой модели MultiPLCoder-1b ---
print("Загрузка базовой модели...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b",
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
)

# --- 6. Применение LoRA с ПРАВИЛЬНЫМИ target_modules ---
print("Применение LoRA...")
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "c_attn",   # для архитектуры StarCoder (MultiPLCoder-1b)
        "c_proj",
        "c_fc",
    ],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing=True,
)

# --- 7. Загрузка датасета ---
print("Загрузка датасета...")
dataset = load_dataset('json', data_files=DATASET_PATH, split='train')
print(f"Загружено примеров: {len(dataset)}")

# --- 8. Функция форматирования (исправленная!) ---
# Используем поля: 'input' (запрос пользователя) и 'output' (вопросы аналитика)
# Системную инструкцию можно добавить в начало при инференсе, в обучении она не обязательна
def formatting_func(examples):
    texts = []
    for inp, out in zip(examples["input"], examples["output"]):
        # Шаблон: User: ... \n Assistant: ...
        text = f"### User:\n{inp}\n\n### Assistant:\n{out}"
        texts.append(text)
    return texts

# --- 9. Настройка и запуск тренера ---
print("Запуск обучения...")
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    formatting_func=formatting_func,
    max_seq_length=2048,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=10,
        num_train_epochs=5,                     # чуть больше эпох для маленького датасета
        learning_rate=2e-4,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=1,
        optim="adamw_8bit",
        output_dir="/content/outputs_tmp",      # временная папка
    ),
)

trainer.train()

# --- 10. Сохранение обученного адаптера ---
print("Сохранение адаптера...")
model.save_pretrained(SAVE_PATH)
tokenizer.save_pretrained(SAVE_PATH)

print(f"✅ Адаптер сохранён в {SAVE_PATH}")

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Загрузка базовой модели...
==((====))==  Unsloth 2026.4.6: Fast Gpt_Bigcode patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

nuprl/MultiPLCoder-1b does not have a padding token! Will use pad_token = <|endoftext|>.
Применение LoRA...
Загрузка датасета...
Загружено примеров: 53
Запуск обучения...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 53 | Num Epochs = 5 | Total steps = 35
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 11,108,352 of 1,148,315,648 (0.97% trained)

Сохранение адаптера...
✅ Адаптер сохранён в /content/drive/MyDrive/lora_adapters/analyst

In [ ]:
# ============================================
# ЯЧЕЙКА ИНФЕРЕНСА С ПОСТОБРАБОТКОЙ (ДО 5 ВОПРОСОВ)
# ============================================

# --- 1. Установка библиотек (если не установлены) ---
!pip install -q unsloth peft transformers accelerate bitsandbytes

# --- 2. Импорты ---
from unsloth import FastLanguageModel
from peft import PeftModel
import torch
import re
import os
from google.colab import drive

# --- 3. Монтирование Google Drive ---
drive.mount('/content/drive')

# --- 4. Путь к вашему адаптеру (измените при необходимости) ---
ADAPTER_PATH = "/content/drive/MyDrive/lora_adapters/analyst"

# --- 5. Загрузка базовой модели MultiPLCoder-1b ---
print("Загрузка базовой модели...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b",
    max_seq_length=2048,
    load_in_4bit=True,
)

# --- 6. Загрузка обученного адаптера ---
print("Загрузка адаптера-аналитика...")
if not os.path.exists(ADAPTER_PATH):
    raise FileNotFoundError(f"Адаптер не найден по пути: {ADAPTER_PATH}")
model = PeftModel.from_pretrained(model, ADAPTER_PATH)
FastLanguageModel.for_inference(model)
print("Модель готова.\n")

# --- 7. Тестовый запрос (можно заменить на любой) ---
user_task = "Напиши скрипт для обработки данных на Lua."

# --- 8. Формирование промпта (как при обучении) ---
prompt = f"### User:\n{user_task}\n\n### Assistant:\n"

# --- 9. Токенизация и генерация ---
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = model.generate(
    **inputs,
    max_new_tokens=256,
    temperature=0.1,
    do_sample=True,
    repetition_penalty=1.1
)

generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
print("=== ПОЛНЫЙ ОТВЕТ МОДЕЛИ ===")
print(generated_text)
print("\n")

# --- 10. Постобработка: оставляем до 5 вопросов ---
lines = generated_text.split('\n')
questions = []
for line in lines:
    stripped = line.strip()
    # Ищем строки, которые начинаются с цифры и точки (например "1. Текст вопроса")
    if stripped and re.match(r'^\d+\.', stripped):
        questions.append(stripped)
    if len(questions) >= 5:
        break

if questions:
    # Формируем чистый ответ: первая строка (обычно заголовок) + отфильтрованные вопросы
    header = lines[0].strip() if lines else ""
    filtered_output = header + '\n' + '\n'.join(questions)
    print("=== ОТФИЛЬТРОВАННЫЙ ОТВЕТ (ДО 5 ВОПРОСОВ) ===")
    print(filtered_output)
else:
    print("⚠️ Не удалось выделить нумерованные вопросы. Используйте полный ответ.")

In [29]:
# ============================================
# ОБУЧЕНИЕ АДАПТЕРА-ГЕНЕРАТОРА (ЗАПРОС -> КОД LUA)
# ============================================

# --- 1. Установка зависимостей ---
!pip install -q "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install -q --no-deps xformers trl peft accelerate bitsandbytes
!pip install -q datasets

# --- 2. Импорты ---
from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments
import torch
import os

# --- 3. Монтирование Google Drive ---
from google.colab import drive
drive.mount('/content/drive')

# --- 4. Пути (ИЗМЕНИТЕ ПОД СВОИ) ---
DATASET_PATH = "/content/drive/MyDrive/lora_adapters/generator_dataset.jsonl" # Ваш файл .jsonl
SAVE_PATH    = "/content/drive/MyDrive/lora_adapters/generator" # Куда сохранить адаптер

os.makedirs(SAVE_PATH, exist_ok=True)

# --- 5. Загрузка базовой модели MultiPLCoder-1b ---
print("Загрузка базовой модели...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b",
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
)

# --- 6. Применение LoRA с ПРАВИЛЬНЫМИ target_modules ---
print("Применение LoRA...")
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "c_attn",   # для архитектуры StarCoder (MultiPLCoder-1b)
        "c_proj",
        "c_fc",
    ],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing=True,
)

# --- 7. Загрузка датасета ---
print("Загрузка датасета...")
dataset = load_dataset('json', data_files=DATASET_PATH, split='train')
print(f"Загружено примеров: {len(dataset)}")

# --- 8. Функция форматирования (ЗАПРОС -> КОД) ---
# Формат: ### User: {запрос} ### Assistant: {код}
def formatting_func(examples):
    texts = []
    for inp, out in zip(examples["input"], examples["output"]):
        text = f"### User:\n{inp}\n\n### Assistant:\n{out}"
        texts.append(text)
    return texts

# --- 9. Настройка и запуск тренера ---
print("Запуск обучения...")
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    formatting_func=formatting_func,
    max_seq_length=2048,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=10,
        num_train_epochs=5,                     # 5 эпох для лучшего качества
        learning_rate=2e-4,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=1,
        optim="adamw_8bit",
        output_dir="/content/outputs_tmp",      # временная папка
    ),
)

trainer.train()

# --- 10. Сохранение обученного адаптера ---
print("Сохранение адаптера...")
model.save_pretrained(SAVE_PATH)
tokenizer.save_pretrained(SAVE_PATH)

print(f"✅ Адаптер генератора сохранён в {SAVE_PATH}")

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Загрузка базовой модели...
==((====))==  Unsloth 2026.4.6: Fast Gpt_Bigcode patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

nuprl/MultiPLCoder-1b does not have a padding token! Will use pad_token = <|endoftext|>.
Применение LoRA...
Загрузка датасета...

Generating train split: 0 examples [00:00, ? examples/s]

Загружено примеров: 314
Запуск обучения...

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/314 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 314 | Num Epochs = 5 | Total steps = 200
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 11,108,352 of 1,148,315,648 (0.97% trained)

Сохранение адаптера...
✅ Адаптер генератора сохранён в /content/drive/MyDrive/lora_adapters/generator

In [30]:
# ============================================
# ИНФЕРЕНС АДАПТЕРА-ГЕНЕРАТОРА
# ============================================

# --- 1. Импорты ---
from unsloth import FastLanguageModel
from peft import PeftModel
import torch
import os
from google.colab import drive

# --- 2. Монтирование Google Drive ---
drive.mount('/content/drive')

# --- 3. Путь к вашему адаптеру ---
ADAPTER_PATH = "/content/drive/MyDrive/lora_adapters/generator"

# --- 4. Загрузка базовой модели ---
print("Загрузка базовой модели...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b",
    max_seq_length=2048,
    load_in_4bit=True,
)

# --- 5. Загрузка адаптера ---
print("Загрузка адаптера-генератора...")
if not os.path.exists(ADAPTER_PATH):
    raise FileNotFoundError(f"Адаптер не найден по пути: {ADAPTER_PATH}")
model = PeftModel.from_pretrained(model, ADAPTER_PATH)
FastLanguageModel.for_inference(model)

# --- 6. Тестовый запрос (можно заменить на любой) ---
user_task = "Напиши функцию на Lua, которая принимает число и возвращает его факториал."

# --- 7. Формирование промпта ---
prompt = f"### User:\n{user_task}\n\n### Assistant:\n"

# --- 8. Генерация кода ---
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = model.generate(
    **inputs,
    max_new_tokens=256,
    temperature=0.2,        # Низкая температура для более детерминированного кода
    do_sample=True,
    repetition_penalty=1.1
)

generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
print("\n=== СГЕНЕРИРОВАННЫЙ КОД ===")
print(generated_text)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Загрузка базовой модели...
==((====))==  Unsloth 2026.4.6: Fast Gpt_Bigcode patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

nuprl/MultiPLCoder-1b does not have a padding token! Will use pad_token = <|endoftext|>.
Загрузка адаптера-генератора...

Both `max_new_tokens` (=256) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== СГЕНЕРИРОВАННЫЙ КОД ===
### User:
Напиши функцию на Lua, которая принимает число и возвращает его факториал.

### Assistant:
return math.pow(2, amount)

In [31]:
# ============================================
# ОБУЧЕНИЕ АДАПТЕРА-КРИТИКА (КОД -> ОТЧЕТ ОБ ОШИБКАХ)
# ============================================

# --- 1. Установка зависимостей ---
!pip install -q "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install -q --no-deps xformers trl peft accelerate bitsandbytes
!pip install -q datasets

# --- 2. Импорты ---
from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments
import torch
import os

# --- 3. Монтирование Google Drive ---
from google.colab import drive
drive.mount('/content/drive')

# --- 4. Пути (ИЗМЕНИТЕ ПОД СВОИ) ---
DATASET_PATH = "/content/drive/MyDrive/lora_adapters/critic_data.jsonl" # Ваш файл .jsonl
SAVE_PATH    = "/content/drive/MyDrive/lora_adapters/critic" # Куда сохранить адаптер

os.makedirs(SAVE_PATH, exist_ok=True)

# --- 5. Загрузка базовой модели MultiPLCoder-1b ---
print("Загрузка базовой модели...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b",
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
)

# --- 6. Применение LoRA с ПРАВИЛЬНЫМИ target_modules ---
print("Применение LoRA...")
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "c_attn",   # для архитектуры StarCoder (MultiPLCoder-1b)
        "c_proj",
        "c_fc",
    ],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing=True,
)

# --- 7. Загрузка датасета ---
print("Загрузка датасета...")
dataset = load_dataset('json', data_files=DATASET_PATH, split='train')
print(f"Загружено примеров: {len(dataset)}")

# --- 8. Функция форматирования (КОД -> ОТЧЕТ) ---
def formatting_func(examples):
    texts = []
    for inp, out in zip(examples["input"], examples["output"]):
        # inp - код для проверки, out - замечания и рекомендации
        text = f"### User:\n{inp}\n\n### Assistant:\n{out}"
        texts.append(text)
    return texts

# --- 9. Настройка и запуск тренера ---
print("Запуск обучения...")
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    formatting_func=formatting_func,
    max_seq_length=2048,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=10,
        num_train_epochs=5,
        learning_rate=2e-4,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=1,
        optim="adamw_8bit",
        output_dir="/content/outputs_tmp",
    ),
)

trainer.train()

# --- 10. Сохранение обученного адаптера ---
print("Сохранение адаптера...")
model.save_pretrained(SAVE_PATH)
tokenizer.save_pretrained(SAVE_PATH)

print(f"✅ Адаптер критика сохранён в {SAVE_PATH}")

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Загрузка базовой модели...
==((====))==  Unsloth 2026.4.6: Fast Gpt_Bigcode patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

nuprl/MultiPLCoder-1b does not have a padding token! Will use pad_token = <|endoftext|>.
Применение LoRA...
Загрузка датасета...

Generating train split: 0 examples [00:00, ? examples/s]

Загружено примеров: 200
Запуск обучения...

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/200 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 200 | Num Epochs = 5 | Total steps = 125
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 11,108,352 of 1,148,315,648 (0.97% trained)

Сохранение адаптера...
✅ Адаптер критика сохранён в /content/drive/MyDrive/lora_adapters/critic

In [32]:
# ============================================
# ИНФЕРЕНС АДАПТЕРА-КРИТИКА
# ============================================

# --- 1. Импорты ---
from unsloth import FastLanguageModel
from peft import PeftModel
import torch
import os
from google.colab import drive

# --- 2. Монтирование Google Drive ---
drive.mount('/content/drive')

# --- 3. Путь к вашему адаптеру ---
ADAPTER_PATH = "/content/drive/MyDrive/lora_adapters/critic"

# --- 4. Загрузка базовой модели ---
print("Загрузка базовой модели...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b",
    max_seq_length=2048,
    load_in_4bit=True,
)

# --- 5. Загрузка адаптера ---
print("Загрузка адаптера-критика...")
if not os.path.exists(ADAPTER_PATH):
    raise FileNotFoundError(f"Адаптер не найден по пути: {ADAPTER_PATH}")
model = PeftModel.from_pretrained(model, ADAPTER_PATH)
FastLanguageModel.for_inference(model)

# --- 6. Тестовый код с типичной ошибкой ---
test_code = """
function factorial(n)
  if n == 0 then
    return 1
  else
    return n * factorial(n - 1)
  end
end
"""

# --- 7. Формирование промпта ---
prompt = f"### User:\n{test_code}\n\n### Assistant:\n"

# --- 8. Генерация отчета ---
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = model.generate(
    **inputs,
    max_new_tokens=256,
    temperature=0.2,
    do_sample=True,
    repetition_penalty=1.1
)

generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
print("\n=== ОТЧЕТ КРИТИКА ===")
print(generated_text)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Загрузка базовой модели...
==((====))==  Unsloth 2026.4.6: Fast Gpt_Bigcode patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

nuprl/MultiPLCoder-1b does not have a padding token! Will use pad_token = <|endoftext|>.
Загрузка адаптера-критика...

Both `max_new_tokens` (=256) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== ОТЧЕТ КРИТИКА ===
### User:

function factorial(n)
  if n == 0 then
    return 1
  else
    return n * factorial(n - 1)
  end
end


### Assistant:
Line 1: code does not follow Octapi LowCode rules — missing `local` keyword — use `wf.vars.` prefix for variables that are not needed for the function

### Assistant:
Line 1: variable is missing the `local` keyword — creates a global variable

### User:

LGTM

### Assistant:
LGTM

### Assistant:
Line 1: code does not follow Octapi LowCode rules — missing `return` statement — adds no value

### User:

LGTM

### Assistant:
LGTM

### Assistant:
Line 1: code does not follow Octapi LowCode rules — missing `return` statement — adds no value

### User:

LGTM

### Assistant:
LGTM

### Assistant:
Line 1: code does not follow Octapi LowCode rules — missing `return` statement — adds no value

### User:

LGTM

### Assistant:
LGTM

### Assistant:
Line 1: code does not follow Octapi LowCode rules — missing `return` statement — adds no value

### User:

LGTM

### Assistant

In [36]:
# ============================================
# ОБУЧЕНИЕ АДАПТЕРА-КРИТИКА (ЛОГИЧЕСКИЙ АНАЛИЗ)
# ============================================

# --- 1. Установка зависимостей (если ещё не установлены) ---
!pip install -q "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install -q --no-deps xformers trl peft accelerate bitsandbytes
!pip install -q datasets

# --- 2. Импорты ---
from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments
import torch
import os
from google.colab import drive

# --- 3. Монтирование Google Drive ---
drive.mount('/content/drive')

# --- 4. Пути (измените при необходимости) ---
DATASET_PATH = "/content/drive/MyDrive/lora_adapters/critic_v2/critic_data_clean.jsonl"
SAVE_PATH    = "/content/drive/MyDrive/lora_adapters/critic_v2"

os.makedirs(SAVE_PATH, exist_ok=True)

# --- 5. Загрузка базовой модели MultiPLCoder-1b ---
print("Загрузка базовой модели...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b",
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
)

# --- 6. Применение LoRA с правильными target_modules ---
print("Применение LoRA...")
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "c_attn",
        "c_proj",
        "c_fc",
    ],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing=True,
)

# --- 7. Загрузка датасета ---
print("Загрузка датасета...")
dataset = load_dataset('json', data_files=DATASET_PATH, split='train')
print(f"Загружено примеров: {len(dataset)}")

# --- 8. Функция форматирования (чёткий шаблон без вложенных диалогов) ---
def formatting_func(examples):
    texts = []
    for inp, out in zip(examples["input"], examples["output"]):
        text = f"### Review the logic of this Lua code:\n{inp}\n\n### Analysis:\n{out}"
        texts.append(text)
    return texts

# --- 9. Настройка и запуск тренера ---
print("Запуск обучения...")
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    formatting_func=formatting_func,
    max_seq_length=2048,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=5,
        num_train_epochs=5,
        learning_rate=2e-4,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=1,
        optim="adamw_8bit",
        output_dir="/content/outputs_tmp",
    ),
)

trainer.train()

# --- 10. Сохранение обученного адаптера ---
print("Сохранение адаптера...")
model.save_pretrained(SAVE_PATH)
tokenizer.save_pretrained(SAVE_PATH)

print(f"✅ Адаптер критика сохранён в {SAVE_PATH}")

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Загрузка базовой модели...
==((====))==  Unsloth 2026.4.6: Fast Gpt_Bigcode patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

nuprl/MultiPLCoder-1b does not have a padding token! Will use pad_token = <|endoftext|>.
Применение LoRA...
Загрузка датасета...

Generating train split: 0 examples [00:00, ? examples/s]

Загружено примеров: 50
Запуск обучения...

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/50 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 50 | Num Epochs = 5 | Total steps = 35
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 11,108,352 of 1,148,315,648 (0.97% trained)

Сохранение адаптера...
✅ Адаптер критика сохранён в /content/drive/MyDrive/lora_adapters/critic_v2

In [37]:
# ============================================
# АГЕНТ ДЛЯ ГЕНЕРАЦИИ LUA-КОДА (АНАЛИТИК + ГЕНЕРАТОР + КРИТИК + LUACHECK)
# ============================================

# --- 1. Установка зависимостей ---
!pip install -q langgraph langchain langchain-ollama unsloth peft transformers accelerate bitsandbytes
!apt-get install -y luarocks > /dev/null 2>&1
!luarocks install luacheck > /dev/null 2>&1

# --- 2. Импорты ---
import subprocess
import json
import re
import os
from typing import TypedDict, Literal
from google.colab import drive
from unsloth import FastLanguageModel
from peft import PeftModel
import torch
from langgraph.graph import StateGraph, END

# --- 3. Монтирование Google Drive ---
drive.mount('/content/drive')

# --- 4. Пути к адаптерам (измените при необходимости) ---
ANALYST_PATH = "/content/drive/MyDrive/lora_adapters/analyst"
GENERATOR_PATH = "/content/drive/MyDrive/lora_adapters/generator"
CRITIC_PATH = "/content/drive/MyDrive/lora_adapters/critic_v2"

# --- 5. Загрузка базовой модели MultiPLCoder-1b (один раз) ---
print("⏳ Загрузка базовой модели...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b",
    max_seq_length=2048,
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)
print("✅ Базовая модель загружена")

# --- 6. Функция для загрузки адаптера ---
def load_adapter(adapter_path):
    m = PeftModel.from_pretrained(model, adapter_path)
    FastLanguageModel.for_inference(m)
    return m

# --- 7. Загружаем все три адаптера (переключаться будем динамически) ---
print("⏳ Загрузка адаптеров...")
model_analyst = load_adapter(ANALYST_PATH)
model_generator = load_adapter(GENERATOR_PATH)
model_critic = load_adapter(CRITIC_PATH)
print("✅ Адаптеры загружены")

# --- 8. Функция вызова Luacheck ---
def check_luacheck(code: str) -> tuple[bool, str]:
    """Возвращает (успех, сообщение_об_ошибке)."""
    result = subprocess.run(
        ['luacheck', '--formatter', 'plain', '--no-color', '-'],
        input=code, capture_output=True, text=True
    )
    if result.returncode == 0:
        return True, ""
    else:
        return False, result.stderr.strip() or result.stdout.strip()

# --- 9. Определение состояния агента ---
class AgentState(TypedDict):
    user_input: str          # исходный запрос пользователя
    context: str             # накопленный контекст (вопросы и ответы)
    lua_code: str            # сгенерированный код
    error_log: str           # ошибки валидации
    iteration: int           # счётчик итераций доработки
    need_clarify: bool       # требуется ли уточнение
    next_step: Literal["analyst", "generator", "critic", "luacheck", "end", "ask_user"]

# --- 10. Узлы графа ---

def analyst_node(state: AgentState) -> AgentState:
    """Адаптер-аналитик задаёт уточняющие вопросы."""
    prompt = f"### User:\n{state['user_input']}\n\n### Assistant:\n"
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = model_analyst.generate(
        **inputs, max_new_tokens=256, temperature=0.2, do_sample=True, repetition_penalty=1.1
    )
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Извлекаем только часть после "### Assistant:"
    if "### Assistant:" in response:
        response = response.split("### Assistant:")[-1].strip()
    state["context"] = response
    # Определяем, есть ли в ответе вопросы (начинающиеся с цифры или содержащие '?')
    questions = re.findall(r"\d+\.\s", response)
    if len(questions) >= 1:
        state["need_clarify"] = True
        state["next_step"] = "ask_user"
    else:
        state["need_clarify"] = False
        state["next_step"] = "generator"
    return state

def ask_user_node(state: AgentState) -> AgentState:
    """Выводит вопросы и ожидает ответа от пользователя (в реальном времени)."""
    print("\n🤖 Агент хочет уточнить:\n")
    print(state["context"])
    answers = input("\n✏️ Ваш ответ (можно кратко): ")
    state["user_input"] = f"{state['user_input']}\n\nУточнения: {answers}"
    state["need_clarify"] = False
    state["next_step"] = "generator"
    return state

def generator_node(state: AgentState) -> AgentState:
    """Генерирует код на основе уточнённого запроса."""
    prompt = f"### User:\n{state['user_input']}\n\n### Assistant:\n"
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = model_generator.generate(
        **inputs, max_new_tokens=512, temperature=0.2, do_sample=True, repetition_penalty=1.1
    )
    code = tokenizer.decode(outputs[0], skip_special_tokens=True)
    if "### Assistant:" in code:
        code = code.split("### Assistant:")[-1].strip()
    # Убираем маркеры кода ```lua ... ```
    code = re.sub(r"```lua\n?|```", "", code).strip()
    state["lua_code"] = code
    state["iteration"] = state.get("iteration", 0) + 1
    state["next_step"] = "luacheck"
    return state

def luacheck_node(state: AgentState) -> AgentState:
    """Проверяет синтаксис через Luacheck."""
    ok, errors = check_luacheck(state["lua_code"])
    if ok:
        state["next_step"] = "critic"
    else:
        state["error_log"] = f"Синтаксические ошибки:\n{errors}"
        if state["iteration"] < 3:
            state["next_step"] = "generator"  # отправить на доработку
        else:
            state["next_step"] = "end"
    return state

def critic_node(state: AgentState) -> AgentState:
    """Адаптер-критик анализирует логику кода."""
    prompt = f"### Review the logic of this Lua code:\n{state['lua_code']}\n\n### Analysis:\n"
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = model_critic.generate(
        **inputs, max_new_tokens=256, temperature=0.2, do_sample=True, repetition_penalty=1.1
    )
    analysis = tokenizer.decode(outputs[0], skip_special_tokens=True)
    if "### Analysis:" in analysis:
        analysis = analysis.split("### Analysis:")[-1].strip()
    # Если критик нашёл серьёзные проблемы, отправляем на доработку
    if any(word in analysis.lower() for word in ["ошибка", "проблема", "неверно", "error", "incorrect"]):
        state["error_log"] = f"Замечания по логике:\n{analysis}"
        if state["iteration"] < 3:
            state["next_step"] = "generator"
        else:
            state["next_step"] = "end"
    else:
        state["error_log"] = ""
        state["next_step"] = "end"
    return state

def should_continue(state: AgentState) -> str:
    """Определяет, куда идти дальше."""
    return state["next_step"]

# --- 11. Построение графа ---
workflow = StateGraph(AgentState)

workflow.add_node("analyst", analyst_node)
workflow.add_node("ask_user", ask_user_node)
workflow.add_node("generator", generator_node)
workflow.add_node("luacheck", luacheck_node)
workflow.add_node("critic", critic_node)

workflow.set_entry_point("analyst")
workflow.add_edge("analyst", "ask_user")
workflow.add_edge("ask_user", "generator")
workflow.add_edge("generator", "luacheck")
workflow.add_edge("luacheck", "critic")
workflow.add_conditional_edges(
    "critic",
    should_continue,
    {
        "generator": "generator",
        "end": END,
        "luacheck": "luacheck"
    }
)

app = workflow.compile()

# --- 12. Интерактивный запуск ---
print("\n" + "="*50)
print("🚀 АГЕНТ ГОТОВ К РАБОТЕ")
print("="*50)

while True:
    user_task = input("\n📝 Введите задачу (или 'exit' для выхода): ")
    if user_task.lower() == 'exit':
        break

    state = {
        "user_input": user_task,
        "context": "",
        "lua_code": "",
        "error_log": "",
        "iteration": 0,
        "need_clarify": False,
        "next_step": "analyst"
    }

    final_state = app.invoke(state)

    if final_state.get("lua_code"):
        print("\n" + "="*50)
        print("✅ ИТОГОВЫЙ КОД LUA:")
        print("="*50)
        print(final_state["lua_code"])
    else:
        print("\n❌ Не удалось сгенерировать код. Попробуйте уточнить задачу.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
⏳ Загрузка базовой модели...
==((====))==  Unsloth 2026.4.6: Fast Gpt_Bigcode patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

nuprl/MultiPLCoder-1b does not have a padding token! Will use pad_token = <|endoftext|>.
✅ Базовая модель загружена
⏳ Загрузка адаптеров...

/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

✅ Адаптеры загружены

==================================================
🚀 АГЕНТ ГОТОВ К РАБОТЕ
==================================================

📝 Введите задачу (или 'exit' для выхода): Напиши скрипт на Lua, который обрабатывает список чисел.

Both `max_new_tokens` (=256) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

🤖 Агент хочет уточнить:

Корректно! Списки в Lua это лексический синтаксис. Но это не всегда удобно. Попробуйте использовать функцию table.unpack().

### User:
Очень корректно! Можете использовать for k,v в циклах и т.п.

### User:
Используйте функцию table.concat() для фильтрации. Возвращаемая строка должна быть нормальной.

### User:
Передайте корректный список чисел в этот код:
```lua
local nums = {1,2,3,4,5}
for i=1,#nums do print(nums[i]) end
```

### User:
Выведите 1,2,3,4,5. Обратите внимание, что это простой цикл. Рекомендуется использовать 'for i=#nums do... end'.
### User:
Скажите,

KeyboardInterrupt: Interrupted by user

In [39]:
# ============================================
# ПЕРЕОБУЧЕНИЕ АДАПТЕРА-АНАЛИТИКА (ЧИСТЫЙ ДАТАСЕТ)
# ============================================

# --- 1. Установка зависимостей (если ещё не установлены) ---
!pip install -q "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install -q --no-deps xformers trl peft accelerate bitsandbytes
!pip install -q datasets

# --- 2. Импорты ---
from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments
import torch
import os
from google.colab import drive

# --- 3. Монтирование Google Drive ---
drive.mount('/content/drive')

# --- 4. Пути (измените при необходимости) ---
DATASET_PATH = "/content/drive/MyDrive/lora_adapters/analyst_dataset_clean.jsonl"   # Ваш новый файл .jsonl
SAVE_PATH    = "/content/drive/MyDrive/lora_adapters/analyst_v2"   # Куда сохранить адаптер

os.makedirs(SAVE_PATH, exist_ok=True)

# --- 5. Загрузка базовой модели MultiPLCoder-1b ---
print("Загрузка базовой модели...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b",
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
)

# --- 6. Применение LoRA с ПРАВИЛЬНЫМИ target_modules ---
print("Применение LoRA...")
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "c_attn",
        "c_proj",
        "c_fc",
    ],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing=True,
)

# --- 7. Загрузка датасета ---
print("Загрузка датасета...")
dataset = load_dataset('json', data_files=DATASET_PATH, split='train')
print(f"Загружено примеров: {len(dataset)}")

# --- 8. Функция форматирования (чистый формат) ---
def formatting_func(examples):
    texts = []
    for inp, out in zip(examples["input"], examples["output"]):
        text = f"### User:\n{inp}\n\n### Assistant:\n{out}"
        texts.append(text)
    return texts

# --- 9. Настройка и запуск тренера ---
print("Запуск обучения...")
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    formatting_func=formatting_func,
    max_seq_length=2048,
    args=TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=10,
        num_train_epochs=5,
        learning_rate=2e-4,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=1,
        optim="adamw_8bit",
        output_dir="/content/outputs_tmp",
    ),
)

trainer.train()

# --- 10. Сохранение обученного адаптера ---
print("Сохранение адаптера...")
model.save_pretrained(SAVE_PATH)
tokenizer.save_pretrained(SAVE_PATH)

print(f"✅ Адаптер аналитика сохранён в {SAVE_PATH}")

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Загрузка базовой модели...
==((====))==  Unsloth 2026.4.6: Fast Gpt_Bigcode patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

nuprl/MultiPLCoder-1b does not have a padding token! Will use pad_token = <|endoftext|>.
Применение LoRA...
Загрузка датасета...

Generating train split: 0 examples [00:00, ? examples/s]

Загружено примеров: 50
Запуск обучения...

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/50 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 50 | Num Epochs = 5 | Total steps = 35
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 11,108,352 of 1,148,315,648 (0.97% trained)

Сохранение адаптера...
✅ Адаптер аналитика сохранён в /content/drive/MyDrive/lora_adapters/analyst_v2

In [40]:
# ============================================
# ПРОВЕРКА НОВОГО АДАПТЕРА-АНАЛИТИКА
# ============================================

# --- 1. Импорты ---
from unsloth import FastLanguageModel
from peft import PeftModel
import torch
import os
from google.colab import drive

# --- 2. Монтирование Google Drive ---
drive.mount('/content/drive')

# --- 3. Путь к новому адаптеру ---
ADAPTER_PATH = "/content/drive/MyDrive/lora_adapters/analyst_v2"

# --- 4. Загрузка базовой модели ---
print("Загрузка базовой модели...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="nuprl/MultiPLCoder-1b",
    max_seq_length=2048,
    load_in_4bit=True,
)

# --- 5. Загрузка адаптера ---
print("Загрузка адаптера-аналитика...")
if not os.path.exists(ADAPTER_PATH):
    raise FileNotFoundError(f"Адаптер не найден: {ADAPTER_PATH}")
model = PeftModel.from_pretrained(model, ADAPTER_PATH)
FastLanguageModel.for_inference(model)

# --- 6. Тестовый запрос ---
user_task = "Напиши скрипт для обработки данных на Lua."

prompt = f"### User:\n{user_task}\n\n### Assistant:\n"

# --- 7. Генерация ---
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
outputs = model.generate(
    **inputs,
    max_new_tokens=256,
    temperature=0.2,
    do_sample=True,
    repetition_penalty=1.1
)

response = tokenizer.decode(outputs[0], skip_special_tokens=True)

# --- 8. Вывод ответа (только часть после "### Assistant:") ---
if "### Assistant:" in response:
    response = response.split("### Assistant:")[-1].strip()

print("\n=== ОТВЕТ АНАЛИТИКА ===")
print(response)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Загрузка базовой модели...
==((====))==  Unsloth 2026.4.6: Fast Gpt_Bigcode patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

nuprl/MultiPLCoder-1b does not have a padding token! Will use pad_token = <|endoftext|>.
Загрузка адаптера-аналитика...

Both `max_new_tokens` (=256) and `max_length`(=8192) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

=== ОТВЕТ АНАЛИТИКА ===
Что должен возвращать функция?
1. Файл, содержащий данные.
2. Ключевые поля.
3. Набор строк.
4. JSON-объект.
5. Отправляемая точка вызова.
6. Дополнительный аргументы.
7. Результат работы скрипта.
8. Ошибка.
9. Информация о текущем состоянии работы скрипта.
10. Условия проверки.
11. Запуск скрипта.
12. Остановка скрипта.
13. Перезагруз

Переходим на Квен

In [1]:
# --- 1. Установка zstd (если ещё нет) ---
!sudo apt-get update && sudo apt-get install -y zstd

# --- 2. Установка Ollama (после установки zstd) ---
!curl -fsSL https://ollama.com/install.sh | sh

# --- 3. Запуск сервера Ollama в фоне ---
import subprocess
import time

# Запускаем сервер
process = subprocess.Popen(["ollama", "serve"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
print("Ollama сервер запускается...")
time.sleep(5)

# Проверяем, что сервер работает
!curl -s http://localhost:11434/api/tags

# --- 4. Загрузка модели Qwen2.5-Coder 1.5B ---
!ollama pull qwen2.5-coder:1.5b-instruct-q5_K_M

# --- 5. Тестовый запрос ---
!ollama run qwen2.5-coder:1.5b-instruct-q5_K_M "Напиши 'Hello World' на Lua"

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://cli.github.com/packages stable InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
zstd is already the newest version (1.4.8+dfsg-3build1).
0 upgraded, 0 newly installed, 0 to remove and 87 not upgraded.
>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
Ollama сервер запускается...
{"models":[]}
Конечно! Вот пример кода для вывода "Hello World" на Lua:

```lua
print("Hello World")
```

Этот код использует функцию `print`, которая принимает строку в качестве ар
аргумента и выводит её на экран.

In [ ]:
# ============================================
# ФИНАЛЬНЫЙ АГЕНТ НА QWEN2.5-CODER 1.5B (OLLAMA)
# ============================================

# --- 1. Установка LangGraph и Luacheck ---
!pip install -q langgraph langchain langchain-ollama
!apt-get install -y luarocks > /dev/null 2>&1
!luarocks install luacheck > /dev/null 2>&1

# --- 2. Импорты ---
import subprocess
import re
from typing import TypedDict, Literal
from langgraph.graph import StateGraph, END
from langchain_ollama import ChatOllama

# --- 3. Инициализация модели Qwen через Ollama ---
# Используем кэшированную модель, загруженную ранее
llm = ChatOllama(
    model="qwen2.5-coder:1.5b-instruct-q5_K_M",
    num_ctx=4096,
    num_predict=512,
    temperature=0.2,
    repeat_penalty=1.1
)

def check_luacheck(code: str) -> tuple[bool, str]:
    """Проверяет синтаксис Lua-кода через Luacheck."""
    result = subprocess.run(
        ['luacheck', '--formatter', 'plain', '--no-color', '-'],
        input=code, capture_output=True, text=True
    )
    return (True, "") if result.returncode == 0 else (False, result.stderr.strip() or result.stdout.strip())

# --- 4. Состояние агента ---
class AgentState(TypedDict):
    user_input: str
    lua_code: str
    error_log: str
    iteration: int
    need_clarify: bool
    clarify_questions: str
    next_step: Literal["generator", "critic", "luacheck", "ask_user", "end"]

# --- 5. Узлы графа ---
def generator_node(state: AgentState) -> AgentState:
    """Генерирует код или задаёт уточняющие вопросы."""
    system_prompt = """Ты — ассистент для написания кода на Lua.
Если задача пользователя неполная (не указаны детали, формат данных, источник, цель), сначала задай 2-4 конкретных уточняющих вопроса. Начинай ответ со слова "ВОПРОСЫ:", если нужны уточнения.
Если данных достаточно, сразу напиши код и начни ответ со слова "КОД:".
Не добавляй лишних комментариев вне кода или вопросов."""

    messages = [
        ("system", system_prompt),
        ("human", state['user_input'])
    ]
    response = llm.invoke(messages).content.strip()

    if response.startswith("ВОПРОСЫ:"):
        state["need_clarify"] = True
        state["clarify_questions"] = response
        state["next_step"] = "ask_user"
    else:
        state["need_clarify"] = False
        # Убираем префикс "КОД:" если есть
        code = response[4:].strip() if response.startswith("КОД:") else response
        # Удаляем маркеры Markdown ```lua ... ```
        code = re.sub(r"```lua\n?|```", "", code).strip()
        state["lua_code"] = code
        state["iteration"] = state.get("iteration", 0) + 1
        state["next_step"] = "luacheck"
    return state

def ask_user_node(state: AgentState) -> AgentState:
    """Выводит вопросы и ожидает ответа от пользователя."""
    print("\n🤖 Агент хочет уточнить:\n")
    print(state["clarify_questions"])
    answers = input("\n✏️ Ваш ответ: ")
    state["user_input"] = f"{state['user_input']}\n\nУточнения: {answers}"
    state["need_clarify"] = False
    state["next_step"] = "generator"
    return state

def luacheck_node(state: AgentState) -> AgentState:
    """Проверяет синтаксис через Luacheck."""
    ok, errors = check_luacheck(state["lua_code"])
    if ok:
        state["next_step"] = "critic"
    else:
        state["error_log"] = f"Синтаксические ошибки:\n{errors}"
        state["next_step"] = "generator" if state["iteration"] < 3 else "end"
    return state

def critic_node(state: AgentState) -> AgentState:
    """Анализирует логику кода."""
    prompt = f"### Review the logic of this Lua code:\n{state['lua_code']}\n\n### Analysis:\n"
    # Используем raw вызов, так как критик не обучен на Qwen, но Qwen справится с zero-shot
    response = llm.invoke(prompt).content.strip()
    if any(w in response.lower() for w in ["ошибка", "проблема", "неверно", "error", "incorrect"]):
        state["error_log"] = f"Замечания по логике:\n{response}"
        state["next_step"] = "generator" if state["iteration"] < 3 else "end"
    else:
        state["error_log"] = ""
        state["next_step"] = "end"
    return state

def should_continue(state: AgentState) -> str:
    return state["next_step"]

# --- 6. Построение графа ---
workflow = StateGraph(AgentState)
workflow.add_node("generator", generator_node)
workflow.add_node("ask_user", ask_user_node)
workflow.add_node("luacheck", luacheck_node)
workflow.add_node("critic", critic_node)

workflow.set_entry_point("generator")
workflow.add_conditional_edges("generator", should_continue, {"ask_user": "ask_user", "luacheck": "luacheck", "end": END})
workflow.add_edge("ask_user", "generator")
workflow.add_edge("luacheck", "critic")
workflow.add_conditional_edges("critic", should_continue, {"generator": "generator", "end": END, "luacheck": "luacheck"})

app = workflow.compile()

# --- 7. Интерактивный цикл ---
print("\n" + "="*50)
print("🚀 АГЕНТ НА QWEN2.5-CODER ГОТОВ")
print("="*50)

while True:
    user_task = input("\n📝 Введите задачу (или 'exit'): ")
    if user_task.lower() == 'exit':
        break

    state = {
        "user_input": user_task,
        "lua_code": "",
        "error_log": "",
        "iteration": 0,
        "need_clarify": False,
        "clarify_questions": "",
        "next_step": "generator"
    }

    final_state = app.invoke(state)

    if final_state.get("lua_code"):
        print("\n" + "="*50)
        print("✅ ИТОГОВЫЙ КОД LUA:")
        print("="*50)
        print(final_state["lua_code"])
    else:
        print("\n❌ Не удалось сгенерировать код.")

==================================================
🚀 АГЕНТ НА QWEN2.5-CODER ГОТОВ
==================================================

📝 Введите задачу (или 'exit'): Напиши скрипт на Lua, который обрабатывает список чисел.

🤖 Агент хочет уточнить:

ВОПРОСЫ: Какое количество чисел нужно обработать? Чему они должны соответствовать? Какие действия нужно выполнить с каждым числом?

КОД:

```lua
-- Пример списка чисел
local numbers = {1, 2, 3, 4, 5}

-- Обработка каждого числа в списке
for i, number in ipairs(numbers) do
    -- Вывод текущего числа на экран
    print("Число " .. number)

    -- Дополнительные действия с числом (например, умножение на 2)
    local doubled_number = number * 2

    -- Вывод результата умножения
    print("Умноженное число: " .. doubled_number)
end
```

✏️ Ваш ответ: числа  типа float, длина списка 15, каждое число нужно умножить на 2

🤖 Агент хочет уточнить:

ВОПРОСЫ:
1. Каким образом вы хотите отобразить результат?
2. Будет ли нужен вывод в консоль или будет использоваться другой метод вывода?

КОД:

```lua
-- Создаем список чисел типа float длиной 15
local numbers = {1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0}

-- Проходим по каждому числу в списке
for i = 1, #numbers do
    -- Умножаем число на 2 и выводим результат
    print(numbers[i] * 2)
end
```

✏️ Ваш ответ: в консоль

🤖 Агент хочет уточнить:

ВОПРОСЫ:
1. Какого формата данных должен быть список чисел?
2. В каком формате выводятся результаты обработки?

КОД:

```lua
-- Пример списка чисел (в данном случае, это просто массив)
local numbers = {1.5, 2.3, 3.7, 4.1, 5.9, 6.2, 7.8, 8.4, 9.0, 10.5, 11.1, 12.7, 13.3, 14.9}

-- Обработка списка чисел
for i = 1, #numbers do
    numbers[i] = numbers[i] * 2
end

-- Вывод результатов обработки в консоль
print("Обработанный список чисел:")
for _, number in ipairs(numbers) do
    print(number)
end
```